### PR TITLE
Remove lock file for geo index for race condition

### PR DESCRIPTION
**Pull request by jiangphcn**
## Overview

This PR is aimed to solve random test failure issue on `should_delete_index_after_deleting_database/1`.

The failure looks 
```
ERROR: Error destroying index: IO error: lock /home/jenkins/workspace/dbnext/label/docker-local-jessie/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-06dea50011c406007b492b7f0336fd4e.1526225701/36397f267810aed735d1b702bd059458/LOCK: Resource temporarily unavailable
Error: Signal 255 :: (null)
/home/jenkins/workspace/dbnext/label/docker-local-jessie/type/paas/src/easton/priv/easton_index[0x42ba5b]
/home/jenkins/workspace/dbnext/label/docker-local-jessie/type/paas/src/easton/priv/easton_index[0x433a22]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f25bd246b45]
/home/jenkins/workspace/dbnext/label/docker-local-jessie/type/paas/src/easton/priv/easton_index[0x40885f]
```
After investigation, we found that the index was first created during `run_hastings_search/1`. However, when trying to delete index as response to deletion of database, the index can't be deleted by calling `leveldb::DestroyDB(dir, opts)`. This doesn't always happen, for example, we don't see the occurrence in local mac environment. However, it happens in build server. 

For sure, the Lock file under index directory was kept by the first process, and this blocks leveldb to destroy instance. As some trail, we try to close previous port or kill the first process. However, this doesn't help.

As current solution, we try to remove local file before trying to destroy index. After that, we didn't see the failure of `should_delete_index_after_deleting_database/1` test.

## Testing recommendations

```
make check skip_deps+=couch_epi apps=hastings

hastings_index_test: design_doc_to_index_int_test (module 'hastings_index_test')...[0.078 s] ok
module 'hastings_format'
module 'hastings_format_view'
module 'hastings_bookmark'
module 'hastings_index_manager'
module 'hastings_vacuum'
module 'hastings_httpd_util'
module 'hastings_delete_db_test'
  Hastings Delete Database Tests
    hastings_delete_db_test:65: should_delete_index_after_deleting_database...[0.569 s] ok
    hastings_delete_db_test:104: should_rename_index_after_deleting_database...[0.715 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
    [done in 1.532 s]
  [done in 1.658 s]
module 'hastings_ken_tests'
  Ken Tests
    hastings_ken_tests:55: ken...[0.102 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
    [done in 0.252 s]
  [done in 0.376 s]
module 'hastings_handle_info_tests'
  hastings handle info test
    hastings_handle_info_tests:52: handle_info_test...[1.036 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
    [done in 1.125 s]
  [done in 1.219 s]
=======================================================
  All 5 tests passed.
```
## Related Issues or Pull Requests

N/A

## Checklist

- [X] Code is written and works correctly;
- [X] Changes are covered by tests;
- [X] Documentation reflects the changes;

### CODE REVIEW

**Comment by davisp** [comment]
Did it not work to try and look up the existing index and stop it first? Seems like it'd be better to block the destroy on waiting for the existing indexer to exit rather than just removing the lock file. Granted we are actively trying to destroy the index at that point though I wonder if that would ever leave us in a situation where we couldn't re-create the index if the destroy and previous process were competing on writing to the index directory.

**Comment by jiangphcn** [comment]
Hey Paul, wanted to get more graceful solution as well. I ever tried to add `erlang:port_close(OldPort)` before destroy. However, I still got same error in build server (Lock file related).

**Comment by davisp** [comment]
Do you have the diff for the previous approach? I think the key here is to monitor that port closing better. Exit signals went async at one point so likely we're just pretending like the actual process has ended before its actually closed and released that lock.

Also this is a bit of a race condition between the index seeing that the database has been deleted vs the cleanup code calling so there should likely be some coordination there between the call to destroy and the actual index process.

**Comment by jiangphcn** [comment]
Hey, @davisp @rnewson  please see below to get diff
hasting side: https://github.com/cloudant-labs/hastings/compare/erl20-test-geo-timeout?expand=1
easton side: https://github.com/cloudant-labs/easton/pull/8/commits/832c9d9f3a578436868db9e4d735664e172beaa3

PS: in order to help troubleshooting, i set Q=1 in test suite.

The log in build server can be found from https://build2.cloudant.com/job/dbnext/label=docker-local-wheezy,type=paas/6957/console and part of them are
```
module 'hastings_delete_db_test'
  Hastings Delete Database Tests
    hastings_delete_db_test:66: should_delete_index_after_deleting_database...src/hastings_index.erl:350:<0.17820.4>: hastings_index IdxDir ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-08d8a637e488513931673aa945e7f531.1526363694/36397f267810aed735d1b702bd059458">>

src/hastings_index.erl:351:<0.17820.4>: hastings_index Pid ... 
{rtree,<0.17821.4>}

src/hastings_index.erl:181:<0.17820.4>: Index#h_idx.pid ... 
{rtree,<0.17821.4>}

src/easton_index.erl:108:<0.17820.4>: easton_index close ... 
{rtree,<0.17821.4>}

src/hastings_index.erl:93:<0.17831.4>: before hastings_index:close Pid ... 
{<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-08d8a637e488513931673aa945e7f531.1526363694/36397f267810aed735d1b702bd059458">>,
 {rtree,<0.17821.4>}}

src/easton_index.erl:151:<0.17831.4>: easton_index destroy ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-08d8a637e488513931673aa945e7f531.1526363694/36397f267810aed735d1b702bd059458">>

ERROR: Error destroying index: IO error: lock /home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-08d8a637e488513931673aa945e7f531.1526363694/36397f267810aed735d1b702bd059458/LOCK: Resource temporarily unavailable
Error: Signal 255 :: (null)
/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/src/easton/priv/easton_index(_ZN6easton10show_stackEi+0x8a)[0x42db9b]
/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/src/easton/priv/easton_index[0x435c7d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x2b9c9a273ead]
/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/src/easton/priv/easton_index[0x40aca1]
*failed*
in function hastings_delete_db_test:'-should_delete_index_after_deleting_database/1-fun-2-'/1 (test/hastings_delete_db_test.erl, line 97)
in call from hastings_delete_db_test:'-should_delete_index_after_deleting_database/1-fun-4-'/2 (test/hastings_delete_db_test.erl, line 97)
**error:{assert,[{module,hastings_delete_db_test},
         {line,97},
         {expression,"GeoDirExistsAfter"},
         {expected,false},
         {value,true}]}
  output:<<"">>

src/easton_index.erl:116:<0.17820.4>: easton_index:close down ... 
rtree
```

**Comment by davisp** [comment]
How about something along the lines of these diffs:

https://gist.github.com/davisp/c34f694f659f722c00e19c4b4a87c49a

**Comment by davisp** [comment]
Big note that I didn't do things like try and compile those diffs but they should show the general intent. It still relies on knowing about the LOCK file in a leveldb instance but it seems a bit better to not try and interfere with it outside of LevelDB itself.

**Comment by jiangphcn** [comment]
hi Paul @davisp I adjusted your change to run and current diff was added to your gist https://gist.github.com/davisp/c34f694f659f722c00e19c4b4a87c49a.

Unfortunately, we didn't see the deletion of Lock after waiting for 5 seconds.  The log can be found at https://build2.cloudant.com/job/dbnext/label=docker-local-wheezy,type=paas/6959/console

Part of them are
```
module 'hastings_delete_db_test'
  Hastings Delete Database Tests
    hastings_delete_db_test:66: should_delete_index_after_deleting_database...src/hastings_index.erl:360:<0.17421.4>: hastings_index IdxDir ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458">>

src/hastings_index.erl:361:<0.17421.4>: hastings_index Pid ... 
{rtree,<0.17422.4>}

src/hastings_index.erl:364:<0.17421.4>: hastings_index {DbFullName, Sig} ... 
{<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872">>,
 <<"36397f267810aed735d1b702bd059458">>}

src/hastings_index.erl:191:<0.17421.4>: Index#h_idx.pid ... 
{rtree,<0.17422.4>}

src/easton_index.erl:110:<0.17421.4>: easton_index close ... 
{rtree,<0.17422.4>}

src/hastings_index.erl:97:<0.17432.4>: hasting_index sig_from_directory ... 
{<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872">>,
 <<"36397f267810aed735d1b702bd059458">>}

src/hastings_index.erl:100:<0.17432.4>: before hastings_index:stop Pid ... 
<0.17422.4>

src/easton_index.erl:118:<0.17421.4>: easton_index:close down ... 
rtree

src/easton_index.erl:153:<0.17432.4>: easton_index destroy ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458">>

src/easton_index.erl:167:<0.17432.4>: easton_index before wait_for_local_release ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

*failed*
in function meck_proc:wait/6 (src/meck_proc.erl, line 169)
in call from hastings_delete_db_test:'-should_delete_index_after_deleting_database/1-fun-4-'/2 (test/hastings_delete_db_test.erl, line 89)
**error:timeout
  output:<<"">>

src/easton_index.erl:819:<0.17432.4>: wait_for_lock_release LockFile ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-26ca4ba5fbf439e86fbb45c813cb42e6.1526448872/36397f267810aed735d1b702bd059458/LOCK">>

    hastings_delete_db_test:105: should_rename_index_after_deleting_database...src/hastings_index.erl:360:<0.17533.4>: hastings_index IdxDir ... 
<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-08b8c9d91fbbc21f5196b9a2f9ad8308.1526448877/36397f267810aed735d1b702bd059458">>

src/hastings_index.erl:361:<0.17533.4>: hastings_index Pid ... 
{rtree,<0.17534.4>}

src/hastings_index.erl:364:<0.17533.4>: hastings_index {DbFullName, Sig} ... 
{<<"/home/jenkins/workspace/dbnext/label/docker-local-wheezy/type/paas/tmp/data/shards/00000000-ffffffff/eunit-test-db-08b8c9d91fbbc21f5196b9a2f9ad8308.1526448877">>,
 <<"36397f267810aed735d1b702bd059458">>}

src/hastings_index.erl:191:<0.17533.4>: Index#h_idx.pid ... 
{rtree,<0.17534.4>}

src/easton_index.erl:110:<0.17533.4>: easton_index close ... 
{rtree,<0.17534.4>}

[0.725 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
    [done in 6.750 s]
  [done in 6.887 s]
module 'hastings_ken_tests'
  Ken Tests
    hastings_ken_tests:55: ken...*timed out*
    undefined
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
  [done in 5.175 s]
[done in 5.303 s]
module 'hastings_handle_info_tests'
hastings handle info test
  hastings_handle_info_tests:52: handle_info_test...[1.035 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
  [done in 1.112 s]
[done in 1.212 s]
=======================================================
  Failed: 1.  Skipped: 0.  Passed: 3.
One or more tests were cancelled.
```

**Comment by davisp** [comment]
Ohhh derp. That's my bad. Its using flock under the covers so it doesn't actually remove that file. Googling quickly I'm also not finding an Erlang implementation of flock to do that test our selves. I'll read back through this later to see if we can't find a decent way to monitor whether we've still got the index open or not. The downside is that we're racing the db deletion side so it may not always be possible to get ahold of the index before we try and destroy it which is really throwing a wrench in the gears here.

**Comment by nickva** [comment]
Alternative approach https://github.com/cloudant-labs/hastings/pull/21

**Comment by jiangphcn** [comment]
Closed with cloudant-labs/hastings#21

**Pull request closed without merging**
